/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wcrawler.GUI;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import wcrawler.core.CrawlConfigurationHandler;
import wcrawler.crawler.*;
import wcrawler.information.*;

/**
 *
 * @author Vo Anh
 */
public class WcrawlerManager extends javax.swing.JFrame {

    private FrmCrawlerStart crawlerStart;
    private frmCrawlerOption crawlerOption;
    private CrawlCreator crawlCreator;
    private CrawlConfiguration crawlConfiguration;
    
    /**
     * Creates new form WcrawlerManager
     */
    public WcrawlerManager() {
        initComponents();
        //set icon
        Image icon = Toolkit.getDefaultToolkit().getImage("./resource/icon_main.png");
        this.setIconImage(icon);
        //display in the center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
           
        //load config
        CrawlConfigurationHandler crawlConfigurationHandler = new CrawlConfigurationHandler();
        crawlConfiguration = crawlConfigurationHandler.loadCrawlConfigFromXml();
        
        //creat start and option form
        crawlerStart = new FrmCrawlerStart(this,crawlConfiguration);
        crawlerStart.setVisible(false);

        crawlerOption = new frmCrawlerOption(this,crawlConfiguration);
        crawlerOption.setVisible(false);

        //Set Button enable when formload
        btnStart.setEnabled(true);
        btnPause.setEnabled(false);
        btnResume.setEnabled(false);
        btnStop.setEnabled(false);
        btnOption.setEnabled(true);
        //init other form
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCrawler = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lbStart = new javax.swing.JLabel();
        lbPause = new javax.swing.JLabel();
        lbResume = new javax.swing.JLabel();
        lbStop = new javax.swing.JLabel();
        btnOption = new javax.swing.JButton();
        lbOption = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vo Anh\\Documents\\NetBeansProjects\\SWD01\\crawlergroup1\\wcrawler\\resource\\download.png")); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnPause.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vo Anh\\Documents\\NetBeansProjects\\SWD01\\crawlergroup1\\wcrawler\\resource\\pause.png")); // NOI18N
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnResume.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vo Anh\\Documents\\NetBeansProjects\\SWD01\\crawlergroup1\\wcrawler\\resource\\resume.png")); // NOI18N
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });

        btnStop.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vo Anh\\Documents\\NetBeansProjects\\SWD01\\crawlergroup1\\wcrawler\\resource\\resume.png")); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        lbStart.setText("Start");

        lbPause.setText("Pause");

        lbResume.setText("Resume");

        lbStop.setText("Stop");

        btnOption.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vo Anh\\Documents\\NetBeansProjects\\SWD01\\crawlergroup1\\wcrawler\\resource\\option.png")); // NOI18N
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });

        lbOption.setText("Option");

        javax.swing.GroupLayout pnlCrawlerLayout = new javax.swing.GroupLayout(pnlCrawler);
        pnlCrawler.setLayout(pnlCrawlerLayout);
        pnlCrawlerLayout.setHorizontalGroup(
            pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrawlerLayout.createSequentialGroup()
                .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrawlerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCrawlerLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbStart)))
                .addGap(26, 26, 26)
                .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCrawlerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbPause)))
                .addGap(25, 25, 25)
                .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCrawlerLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbResume)))
                .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrawlerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnOption, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCrawlerLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lbStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbOption)
                        .addGap(48, 48, 48))))
        );
        pnlCrawlerLayout.setVerticalGroup(
            pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrawlerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCrawlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbStart)
                        .addComponent(lbPause)
                        .addComponent(lbResume)
                        .addComponent(lbStop)))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCrawler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCrawler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:

        btnResume.setEnabled(true);
        btnPause.setEnabled(false);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        // TODO add your handling code here:

        btnResume.setEnabled(false);
        btnPause.setEnabled(true);
        btnStop.setEnabled(true);
    }//GEN-LAST:event_btnResumeActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:

        btnPause.setEnabled(true);
        btnResume.setEnabled(true);
        btnStart.setEnabled(true);
        btnStop.setEnabled(false);
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        crawlerOption.setVisible(true);
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
       crawlerStart.setVisible(true);
        crawlerStart.Create();
       
        this.setEnabled(false);
        
        //Set enable button pause, resume, stops is true
        btnPause.setEnabled(true);
        btnStop.setEnabled(true);
        btnResume.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WcrawlerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WcrawlerManager().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOption;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lbOption;
    private javax.swing.JLabel lbPause;
    private javax.swing.JLabel lbResume;
    private javax.swing.JLabel lbStart;
    private javax.swing.JLabel lbStop;
    private javax.swing.JPanel pnlCrawler;
    // End of variables declaration//GEN-END:variables
}
